name = "garnet_tool"
version = "1.0.4"
target = "javascript"

description = "Compile gleam to single binary, via Deno and Bun. "
licences = ["MIT"]
[repository]
type = "github"
user = "Comamoca"
repo = "garnet"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
esgleam = ">= 0.6.0 and < 1.0.0"
simplifile = ">= 1.7.0 and < 3.0.0"
spinner = ">= 1.1.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"
gleam_fetch = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 1.0.1 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
# cleam = ">= 1.5.0 and < 2.0.0"
# rad = ">= 1.2.1 and < 2.0.0"

[[rad.tasks]]
path = ["run"]
run = ["gleam", "run"]
